# Site settings
title: Harry Cutts
tagline: Computer scientist, author, and fencer.
description: >
  I'm a recent graduate in Computer Science from the University of Southampton
  currently working at Google, with previous work experience at CERN and
  Snowflake Software. I have a wide variety of interests, including information
  security and user experience design. In my spare time I fence, write fiction,
  and contribute to OpenStreetMap.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.harrycutts.me.uk" # the base hostname & protocol for your site

mailhide_url: https://www.google.com/recaptcha/mailhide/d?k=01sTiyQtbP_RmjnQwd_LL5nA==&c=RLEHvb9LouijKewAugGxCUJrhzMWfhj8iF20ZTeW85U
#twitter_username: jekyllrb
github_username:  HarryCutts
keybase_username: hc

# Build settings
markdown: kramdown
